import {StyleSheet} from 'react-native';
import {colors, effects, spacing, radius, fontSize, stroke} from '../tokens';

export const styles = StyleSheet.create({
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xxl,
    backgroundColor: colors.backgroundBlueSoft,
  },
  container: {flex: 1, backgroundColor: colors.black},
  cameraFill: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  overlay: {
    position: 'absolute',
    top: spacing.tera,
    width: '100%',
    zIndex: 1,
    alignItems: 'center',
    padding: spacing.xxl,
  },
  scanTitle: {
    color: colors.white,
    fontSize: fontSize.title,
    fontWeight: 'bold',
  },
  scanSub: {color: colors.white, textAlign: 'center', marginTop: spacing.md},
  cancelScanButton: {
    marginTop: spacing.xxl,
    backgroundColor: colors.scannerOverlayDanger,
    paddingHorizontal: spacing.xxl,
    paddingVertical: spacing.md,
    borderRadius: radius.xxl,
  },
  cancelScanButtonText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: fontSize.base,
  },
  scannerFrame: {
    position: 'absolute',
    top: '30%',
    left: '15%',
    width: '70%',
    height: '35%',
    borderWidth: stroke.regular,
    borderColor: colors.success,
    borderRadius: radius.xxl,
    backgroundColor: colors.transparent,
  },
  welcomeContainer: {
    flex: 1,
    backgroundColor: colors.backgroundBlueSoft,
  },
  welcomeContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.huge,
  },
  welcomeEmoji: {
    fontSize: fontSize.emoji,
    marginBottom: spacing.xxl,
  },
  welcomeTitle: {
    fontSize: fontSize.display,
    fontWeight: 'bold',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: spacing.xl,
  },
  welcomeSubtitle: {
    fontSize: fontSize.xl,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.huge,
    paddingHorizontal: spacing.xxl,
  },
  instructionsBox: {
    backgroundColor: colors.card,
    padding: spacing.xxl,
    borderRadius: radius.xl,
    width: '100%',
    marginBottom: spacing.huge,
    elevation: effects.elevationSm,
  },
  instructionsTitle: {
    fontSize: fontSize.xl,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: spacing.xl,
  },
  instructionStep: {
    fontSize: fontSize.base,
    color: colors.textSecondary,
    marginBottom: spacing.sm,
    lineHeight: spacing.xxl,
  },
  scanButton: {
    backgroundColor: colors.success,
    paddingHorizontal: spacing.huge,
    paddingVertical: spacing.xl,
    borderRadius: radius.round,
    elevation: effects.elevationLg,
  },
  scanButtonText: {
    color: colors.white,
    fontSize: fontSize.xxl,
    fontWeight: 'bold',
  },
  shieldContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.backgroundBlueSoft,
    padding: spacing.xxl,
  },
  menuButton: {
    position: 'absolute',
    top: spacing.xxl,
    right: spacing.xxl,
    padding: spacing.md,
    zIndex: 10,
  },
  menuIcon: {
    fontSize: fontSize.display,
    color: colors.textPrimary,
    fontWeight: 'bold',
  },
  shieldIcon: {
    fontSize: fontSize.icon,
  },
  iconCircle: {
    width: 120,
    height: 120,
    borderRadius: radius.circle,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: effects.elevationXl,
  },
  shieldTitle: {
    fontSize: fontSize.hero,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginTop: spacing.huge,
  },
  shieldStatus: {
    fontSize: fontSize.xl,
    color: colors.textSecondary,
    marginTop: spacing.md,
    textAlign: 'center',
  },
  linkedBadge: {
    marginTop: spacing.mega,
    padding: spacing.md,
    backgroundColor: colors.successBg,
    borderRadius: radius.xxl,
  },
  linkedText: {
    color: colors.successDeep,
    fontSize: fontSize.md,
    fontWeight: 'bold',
  },
  permissionBadge: {
    marginTop: spacing.xxl,
    padding: spacing.xl,
    borderRadius: radius.lg,
    width: '90%',
    flexDirection: 'row',
    alignItems: 'center',
    elevation: effects.elevationSm,
  },
  permissionGranted: {
    backgroundColor: colors.successBg,
    borderWidth: stroke.regular,
    borderColor: colors.permissionGrantedBorder,
  },
  permissionDenied: {
    backgroundColor: colors.dangerSoft,
    borderWidth: stroke.regular,
    borderColor: colors.permissionDeniedBorder,
  },
  permissionIcon: {
    fontSize: fontSize.display,
    marginRight: spacing.lg,
  },
  permissionTextContainer: {
    flex: 1,
  },
  permissionTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: colors.permissionTitle,
    marginBottom: spacing.xxs,
  },
  permissionSubtitle: {
    fontSize: fontSize.sm,
    color: colors.permissionSubtitle,
    marginBottom: 6,
  },
  permissionAction: {
    fontSize: fontSize.md,
    color: colors.permissionAction,
    fontWeight: 'bold',
    textDecorationLine: 'underline',
  },
  permissionDeactivate: {
    fontSize: fontSize.sm,
    color: colors.permissionSubtitle,
    fontStyle: 'italic',
  },
  actionsContainer: {
    marginTop: spacing.giga,
    width: '100%',
    paddingHorizontal: spacing.xxl,
  },
  unlinkButton: {
    backgroundColor: colors.warning,
    padding: spacing.xl,
    borderRadius: radius.md,
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  unlinkButtonText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: fontSize.xl,
  },
  logoutButton: {
    backgroundColor: colors.danger,
    padding: spacing.xl,
    borderRadius: radius.md,
    alignItems: 'center',
  },
  logoutButtonText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: fontSize.xl,
  },
  retryButton: {
    backgroundColor: colors.success,
    padding: spacing.xl,
    borderRadius: radius.md,
    marginTop: spacing.xxl,
  },
  retryButtonText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: fontSize.xl,
  },
  cancelButton: {
    backgroundColor: colors.textSecondary,
    padding: spacing.xl,
    borderRadius: radius.md,
    marginTop: spacing.md,
  },
  cancelButtonText: {
    color: colors.white,
    fontWeight: 'bold',
    fontSize: fontSize.xl,
  },
  errorText: {
    fontSize: fontSize.xxl,
    color: colors.danger,
    fontWeight: 'bold',
    marginBottom: spacing.md,
  },
  errorSubtext: {
    fontSize: fontSize.base,
    color: colors.textSecondary,
    textAlign: 'center',
  },
});
