import {StyleSheet} from 'react-native';
import {colors, effects, spacing, radius, fontSize, stroke} from '../tokens';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: colors.backgroundSoft},
  header: {
    padding: spacing.xxl,
    backgroundColor: colors.white,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    elevation: effects.elevationMd,
  },
  title: {
    fontSize: fontSize.title,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  subtitle: {
    fontSize: fontSize.md,
    color: colors.success,
    fontWeight: 'bold',
    marginTop: spacing.xxs,
  },
  card: {
    backgroundColor: colors.card,
    padding: spacing.xxl - spacing.xxs,
    marginHorizontal: spacing.xl + spacing.xs,
    marginVertical: spacing.sm,
    borderRadius: radius.lg,
    elevation: effects.elevationSm,
  },
  highRiskCard: {
    backgroundColor: colors.dangerBgSoft,
    borderLeftWidth: stroke.accent,
    borderLeftColor: colors.danger,
  },
  mediumRiskCard: {
    backgroundColor: colors.warningBgSoft,
    borderLeftWidth: stroke.accent,
    borderLeftColor: colors.warning,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  sender: {
    fontSize: fontSize.lg,
    fontWeight: 'bold',
    color: colors.textPrimary,
    flex: 1,
  },
  highRiskText: {color: colors.dangerDark},
  mediumRiskText: {color: colors.warningDeep},
  time: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    marginLeft: spacing.sm,
  },
  message: {
    fontSize: fontSize.lg,
    color: colors.textPrimary,
    lineHeight: fontSize.title,
    marginBottom: spacing.sm,
  },
  riskBadge: {
    backgroundColor: colors.danger,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xs + spacing.xxs,
    borderRadius: radius.sm,
    marginTop: spacing.sm,
    alignSelf: 'flex-start',
  },
  mediumRiskBadge: {
    backgroundColor: colors.warning,
  },
  riskBadgeText: {
    color: colors.white,
    fontSize: fontSize.sm,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  emptyContainer: {alignItems: 'center', marginTop: spacing.peta},
  emptyText: {
    fontSize: fontSize.xl,
    color: colors.textMuted,
    fontWeight: 'bold',
  },
  logoutButton: {
    padding: spacing.sm,
    backgroundColor: colors.dangerSoft,
    borderRadius: radius.xs,
  },
  logoutText: {color: colors.danger, fontSize: fontSize.md, fontWeight: 'bold'},
  clearButton: {
    padding: spacing.sm,
    backgroundColor: colors.warningBgPale,
    borderRadius: radius.sm,
    marginRight: spacing.md,
  },
  clearButtonText: {
    fontSize: fontSize.xxl,
  },
  qrHeaderButton: {
    padding: spacing.sm,
    backgroundColor: colors.backgroundNeutral,
    borderRadius: radius.sm,
    marginRight: spacing.md,
  },
  qrHeaderIcon: {
    fontSize: fontSize.xxxl,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.modalOverlay,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '85%',
    backgroundColor: colors.white,
    borderRadius: radius.xxl,
    padding: spacing.xxxl,
    alignItems: 'center',
    elevation: effects.elevationXl,
  },
  modalTitle: {
    fontSize: fontSize.title,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  modalSub: {
    fontSize: fontSize.base,
    color: colors.textSecondary,
    textAlign: 'center',
    marginVertical: spacing.md,
  },
  qrWrapper: {
    padding: spacing.xl,
    backgroundColor: colors.white,
    marginVertical: spacing.xxl,
  },
  uidText: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    marginBottom: spacing.xxl,
  },
  closeButton: {
    backgroundColor: colors.info,
    paddingHorizontal: spacing.huge,
    paddingVertical: spacing.lg,
    borderRadius: radius.md,
  },
  closeButtonText: {color: colors.white, fontWeight: 'bold'},
  dashboardContainer: {
    padding: spacing.xl,
    backgroundColor: colors.white,
    margin: spacing.xl + spacing.xs,
    borderRadius: radius.xl,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: effects.elevationXs,
  },
  statCard: {
    alignItems: 'center',
    paddingRight: spacing.xl,
    borderRightWidth: stroke.thin,
    borderRightColor: colors.borderSoft,
  },
  statNumber: {
    fontSize: fontSize.display,
    fontWeight: 'bold',
    color: colors.info,
  },
  statLabel: {
    fontSize: fontSize.xs,
    color: colors.textSecondary,
    fontWeight: 'bold',
  },
  childrenList: {flex: 1, paddingLeft: spacing.xl},
  listTitle: {
    fontSize: fontSize.md,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: radius.xs,
  },
  childBadge: {
    backgroundColor: colors.infoSoft,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: radius.md,
    alignSelf: 'flex-start',
    marginBottom: spacing.xs,
  },
  childBadgeSelected: {
    backgroundColor: colors.info,
    borderWidth: stroke.regular,
    borderColor: colors.infoDark,
  },
  childBadgeText: {
    fontSize: fontSize.sm,
    color: colors.info,
    fontWeight: 'bold',
  },
  childBadgeTextSelected: {color: colors.white},
  childBadgeInAlert: {
    backgroundColor: colors.successBgSoftAlt,
    paddingHorizontal: spacing.md,
    paddingVertical: radius.xs,
    borderRadius: radius.sm,
    alignSelf: 'flex-start',
    marginBottom: spacing.sm,
    borderWidth: stroke.thin,
    borderColor: colors.successBorderSoftAlt,
  },
  childBadgeInAlertText: {
    fontSize: fontSize.sm,
    color: colors.successDark,
    fontWeight: 'bold',
  },
  noChildrenText: {
    fontSize: fontSize.sm,
    color: colors.textMuted,
    fontStyle: 'italic',
  },
});
